## name: Rosé Pine
## author: mvllow
## license: MIT
## upstream: https://github.com/rose-pine/kitty/blob/main/dist/rose-pine.conf
## blurb: All natural pine, faux fur and a bit of soho vibes for the classy minimalist

foreground               #e0def4 # semiblanco
background               #191724 # negro
selection_foreground     #e0def4 # semiblanco
selection_background     #403d52 # lavanda oscuro

cursor                   #524f67
cursor_text_color        #e0def4 # semiblanco

url_color                #c4a7e7 # lila

active_tab_foreground    #e0def4 # semiblanco
active_tab_background    #26233a # morado oscuro
inactive_tab_foreground  #6e6a86 # lavanda
inactive_tab_background  #191724 # negro

active_border_color      #98929e # gris lavanda
inactive_border_color    #403d52 # lavanda oscuro

# black
color0   #26233a # morado oscuro
color8   #6e6a86 # lavanda

# red (rosa fuerte opaco)
color1   #a36584
color9   #a36584

# green (verde menta)
color2   #cce8cc
color10  #cce8cc

# yellow (beige mostaza)
color3   #c3b2a2
color11  #c3b2a2

# blue (gris lavanda)
color4   #9490a2
color12  #9490a2

# magenta (lila)
color5   #c4a7e7
color13  #c4a7e7

# cyan (rosita)
color6   #ebbcba
color14  #ebbcba

# white
color7   #e0def4
color15  #e0def4
