$lock_cmd = pidof hyprlock || hyprlock

#pide contraseña al volver
general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = loginctl lock-session
}

#apaga la pantalla por inactividad
listener {
    timeout = 300 #5min
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
