general {
    before_sleep_cmd = swaylock -f
}

listener {
    timeout  = 300
    on-timeout = bash -c 'if [[ "$XDG_CURRENT_DESKTOP" == "niri" ]]; then niri msg action power-off-monitors; else hyprctl dispatch dpms off; fi'
    on-resume  = bash -c 'if [[ "$XDG_CURRENT_DESKTOP" == "niri" ]]; then niri msg action power-on-monitors; else hyprctl dispatch dpms on; fi'
}

listener {
    timeout  = 600
    on-timeout = swaylock -f
}